language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y nasm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -O https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/macosx/nasm-2.14.02-macosx.zip && unzip nasm-2.14.02-macosx.zip && export PATH=$(pwd)/nasm-2.14.02:$PATH; fi

script:
  - bin/fetch-configlet
  - bin/configlet lint --track-id x86-assembly .
  - bin/verify-exercises
