language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y nasm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nasm; fi

script:
  - bin/fetch-configlet
  - bin/configlet lint --track-id x86-assembly .
  - bin/verify-exercises
